# Generated by Django 5.2.7 on 2025-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='reference_code',
            field=models.CharField(default='tttt02000', editable=False, max_length=20, unique=True),
        ),
    ]
